### ISSUE TITLE
Specify primary access URL somewhere?

### ISSUE THREAD

**Issue by tlambert03** [micro-manager/apidoc#3]
Hey @marktsuchida 

was just trying to track down where the [`apidoc.yml` workflow](https://github.com/micro-manager/micro-manager/blob/main/.github/workflows/apidoc.yml) actually publishes the updated MMCore apidocs to.  I see that it pushes to this repo, and that this repo has a gh-pages branch that gets updated.  I also see that this organization's gh-pages URL forwards to micro-manager.org ... 

What I can't tell though... is whether the links in the `APIs` section of micro-manager.org are pointing to these docs:

![Screen Shot 2022-12-01 at 11 32 19 AM](https://user-images.githubusercontent.com/1609449/205107723-47cc43c0-83b4-4a1a-a04f-8b1484e20dd4.png)

If you click the MMCore link, it takes you to https://valelab4.ucsf.edu/~MM/doc/MMCore/html/class_c_m_m_core.html  ... (and the combination of a new URL and the v1.4 in the header made me doubt whether that was current).

So, where does this publish?  And would you consider adding a line like "these docs are published to https://..." to the readme?

**Comment by marktsuchida** [comment]
Yeah, this is work unfinished....
https://micro-manager.org/apidoc/mmstudio/latest/
https://micro-manager.org/apidoc/mmcorej/latest/
https://micro-manager.org/apidoc/MMCore/latest/
https://micro-manager.org/apidoc/MMDevice/latest/
Plus some version-specific ones for mmstudio, but there is no index/toc under `apidoc/`.

We could put an index page at `apidoc/`, or just use a wiki page as the index and redirect `apidoc/` to it (similarly to what I do with the root of download.micro-manager.org).

Also, if you know of any generic tool for publishing multiple versions of API docs (with one of those "switch to version" buttons), I'm all ears.

I'll go and update the links in the sidebar.

**Comment by tlambert03** [comment]
aha!  lovely. thanks!

**Comment by tlambert03** [comment]
> Also, if you know of any generic tool for publishing multiple versions of API docs (with one of those "switch to version" buttons), I'm all ears.

I use [`mike`](https://github.com/jimporter/mike) ... but I think it makes assumptions about the framework (it's designed for [mkdocs](https://www.mkdocs.org/)).  It essentially adds a layer of nesting to your `gh-pages` branch, with folders for each build, and then adds a little javascript switcher to your template to choose between versions.  Inside of each version folder is just a complete build

**Comment by marktsuchida** [comment]
@tlambert03 Thanks, I'll take a look.

Update of micro-manager.org done (https://github.com/micro-manager/micro-manager.github.io/commit/990700bc7ce84202cc625eb2594de3d1008a129b).

**Comment by marktsuchida** [comment]
Added links and some info to README (aadab521de94653e201a30fba433d7b5f6e91e22).
